#!/bin/bash
echo "Getting system level info."
echo "HOSTNAME : `hostname`"
echo "DATE : `date`"
echo "KERNAEL VER : `uname`"
echo "IP : `hostname -i`"
echo ""
echo "DISK : `df -Th`"
echo ""
echo "MEMORY : `free -h`"
